### ISSUE TITLE
Maintaining the project wiki

### ISSUE THREAD

**Issue by prjctimg** [xmlwizard/huetiful#131]
**Is your feature request related to a problem? Please describe.**
The number of npm downloads we have at the moment is not quite in line with my expectations. I had previously hoped to build a community by the end of January but there's still room for improvement. This is why I have opened up a project wiki. It will include tips, guides and further explanations about how this project works

**Describe the solution you'd like**
It would be nice to investigate possible use cases for this project and compile articles on the subjects. This will help people get started faster when using our project.

**Describe alternatives you've considered**
Initially I thought about using codepens but because of the paywall limitations, we'll have to use Gists to showcase some examples.

**Additional context**
If there's anyone interested in helping out, please get in touch

**Comment by prjctimg** [comment]
Stale issue message

**Comment by takanome-dev** [comment]
> This is why I have opened up a project wiki. It will include tips, guides and further explanations about how this project works

+1 for this. I think most of the people would fine this project really cool but might not know when to use it and maybe how to leverage the utilities that it provide.

**Comment by prjctimg** [comment]
> > This is why I have opened up a project wiki. It will include tips, guides and further explanations about how this project works
> 
> +1 for this. I think most of the people would fine this project really cool but might not know when to use it and maybe how to leverage the utilities that it provide.

Thanks for the insight! I have compiled a few example use cases that are currently being edited. The wiki page will be updated by the end of this week when we release. 

Feel free if you have suggested use cases/intergrations you'd like to see included in the wiki. 

I'll update this issue tonight when I push today's changes for review.

**Comment by prjctimg** [comment]
Stale issue message
